USE bazy_danych1;

insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (1, 'United States', 'Sacramento', '872 Chive Place', '95818');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (2, 'United States', 'Jacksonville', '2 Becker Alley', '32204');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (3, 'United States', 'Biloxi', '534 Hoard Place', '39534');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (4, 'United States', 'Tacoma', '28 Farwell Hill', '98442');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (5, 'United States', 'Salt Lake City', '4 Summit Pass', '84170');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (6, 'United States', 'Oklahoma City', '92 Green Hill', '73167');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (7, 'United States', 'Philadelphia', '8911 Gateway Circle', '19172');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (8, 'United States', 'Seattle', '15980 Crest Line Plaza', '98109');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (9, 'United States', 'Grand Rapids', '787 Bayside Junction', '49505');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (10, 'United States', 'Youngstown', '55 Mesta Road', '44505');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (11, 'United States', 'Philadelphia', '25194 Laurel Circle', '19104');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (12, 'United States', 'Lincoln', '68604 Lotheville Circle', '68517');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (13, 'United States', 'Las Vegas', '2 Talmadge Plaza', '89193');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (14, 'United States', 'Sacramento', '983 Chive Center', '94273');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (15, 'United States', 'Brooklyn', '8 Dwight Place', '11254');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (16, 'United States', 'Houston', '728 Dayton Street', '77070');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (17, 'United States', 'Sacramento', '03 Porter Plaza', '94297');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (18, 'United States', 'Alexandria', '4 Bultman Terrace', '22313');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (19, 'United States', 'Mobile', '83 Buell Circle', '36689');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (20, 'United States', 'Tulsa', '599 Londonderry Trail', '74184');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (21, 'United States', 'New York City', '8825 Melody Center', '10160');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (22, 'United States', 'Virginia Beach', '7 Northland Place', '23454');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (23, 'United States', 'Chandler', '080 Welch Way', '85246');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (24, 'United States', 'Tucson', '1746 Dahle Hill', '85743');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (25, 'United States', 'Amarillo', '193 Rusk Terrace', '79105');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (26, 'United States', 'Birmingham', '347 Oak Alley', '35205');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (27, 'United States', 'Chesapeake', '02 Straubel Road', '23324');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (28, 'United States', 'Lincoln', '7 Dawn Place', '68510');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (29, 'United States', 'Pasadena', '5 Stephen Street', '91103');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (30, 'United States', 'Naples', '3 Eliot Lane', '34114');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (31, 'United States', 'Dallas', '39 Mendota Court', '75342');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (32, 'United States', 'Hamilton', '7627 Ludington Trail', '45020');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (33, 'United States', 'Kansas City', '30 Dawn Crossing', '64125');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (34, 'United States', 'Sioux City', '911 Quincy Place', '51105');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (35, 'United States', 'Peoria', '74 Debs Avenue', '61635');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (36, 'United States', 'Saint Louis', '33266 Division Court', '63121');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (37, 'United States', 'Reston', '9079 Becker Lane', '20195');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (38, 'United States', 'Shreveport', '4 Glendale Place', '71161');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (39, 'United States', 'Detroit', '81 Sunfield Street', '48217');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (40, 'United States', 'Washington', '65137 Portage Road', '20436');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (41, 'United States', 'Erie', '012 Goodland Lane', '16505');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (42, 'United States', 'Cedar Rapids', '4 Ludington Center', '52405');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (43, 'United States', 'Roanoke', '5323 Hoffman Road', '24009');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (44, 'United States', 'Huntington', '4 Northwestern Circle', '25775');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (45, 'United States', 'Bellevue', '3 High Crossing Court', '98008');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (46, 'United States', 'Inglewood', '419 Hazelcrest Crossing', '90305');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (47, 'United States', 'Jefferson City', '1 Maywood Way', '65105');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (48, 'United States', 'Palatine', '2 Kipling Street', '60078');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (49, 'United States', 'Mountain View', '571 Fuller Court', '94042');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (50, 'United States', 'Odessa', '7 Macpherson Avenue', '79764');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (51, 'United States', 'Corpus Christi', '56999 Mockingbird Parkway', '78405');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (52, 'United States', 'Savannah', '5773 Rusk Drive', '31422');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (53, 'United States', 'Memphis', '582 Fallview Lane', '38161');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (54, 'United States', 'Youngstown', '23545 South Plaza', '44511');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (55, 'United States', 'New Orleans', '10 Acker Point', '70183');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (56, 'United States', 'Kingsport', '024 Transport Place', '37665');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (57, 'United States', 'Fort Worth', '89079 Anthes Crossing', '76178');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (58, 'United States', 'San Bernardino', '81 Luster Place', '92415');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (59, 'United States', 'Santa Monica', '2721 High Crossing Road', '90410');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (60, 'United States', 'Oklahoma City', '98208 Lukken Park', '73142');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (61, 'United States', 'Anchorage', '84346 Declaration Center', '99599');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (62, 'United States', 'Scottsdale', '25 Golf Course Terrace', '85271');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (63, 'United States', 'Rochester', '01848 Bayside Alley', '14683');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (64, 'United States', 'Portland', '2573 Lukken Junction', '97240');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (65, 'United States', 'Las Cruces', '9 Farwell Road', '88006');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (66, 'United States', 'Hyattsville', '01854 Stuart Street', '20784');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (67, 'United States', 'Tucson', '65928 Elgar Lane', '85754');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (68, 'United States', 'Stockton', '5494 Lotheville Park', '95210');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (69, 'United States', 'Saint Petersburg', '15 Nova Drive', '33710');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (70, 'United States', 'Las Vegas', '1 Farmco Trail', '89193');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (71, 'United States', 'Amarillo', '36 Twin Pines Alley', '79171');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (72, 'United States', 'Fairbanks', '4313 Alpine Park', '99709');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (73, 'United States', 'Erie', '0 Warner Way', '16505');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (74, 'United States', 'Memphis', '0 Elmside Way', '38168');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (75, 'United States', 'Shreveport', '0290 Marquette Plaza', '71115');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (76, 'United States', 'Minneapolis', '3 Spohn Way', '55470');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (77, 'United States', 'Delray Beach', '3 Vermont Crossing', '33448');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (78, 'United States', 'Detroit', '6440 Scoville Circle', '48206');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (79, 'United States', 'Oklahoma City', '9571 Cherokee Plaza', '73129');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (80, 'United States', 'Staten Island', '1783 Lerdahl Avenue', '10310');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (81, 'United States', 'San Francisco', '562 Autumn Leaf Lane', '94121');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (82, 'United States', 'Augusta', '47386 Elgar Crossing', '30905');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (83, 'United States', 'Hartford', '7542 Glacier Hill Court', '06152');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (84, 'United States', 'Dayton', '9903 Vernon Pass', '45440');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (85, 'United States', 'Odessa', '9359 Tennyson Road', '79764');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (86, 'United States', 'Washington', '24631 Cherokee Plaza', '20566');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (87, 'United States', 'Washington', '62 Thompson Drive', '20575');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (88, 'United States', 'West Palm Beach', '05 Warrior Park', '33411');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (89, 'United States', 'Washington', '3010 Oak Lane', '20575');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (90, 'United States', 'Flushing', '815 Ridge Oak Plaza', '11355');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (91, 'United States', 'Santa Cruz', '3396 Coolidge Pass', '95064');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (92, 'United States', 'Boynton Beach', '590 Nobel Junction', '33436');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (93, 'United States', 'Erie', '9 Thompson Junction', '16505');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (94, 'United States', 'Jackson', '2 Dahle Point', '39204');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (95, 'United States', 'Marietta', '7 Algoma Place', '30061');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (96, 'United States', 'Portland', '5 Dawn Junction', '97211');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (97, 'United States', 'Cincinnati', '4 Pankratz Trail', '45213');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (98, 'United States', 'Carson City', '20395 Buell Pass', '89706');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (99, 'United States', 'Staten Island', '24186 Waubesa Drive', '10310');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (100, 'United States', 'Saint Louis', '0108 Sunbrook Way', '63143');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (101, 'United States', 'Pueblo', '6095 Morning Alley', '81010');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (102, 'United States', 'Richmond', '10006 Miller Center', '23272');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (103, 'United States', 'Pueblo', '1 Norway Maple Plaza', '81010');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (104, 'United States', 'Chicago', '367 Boyd Place', '60630');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (105, 'United States', 'Charleston', '82795 Warner Terrace', '25336');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (106, 'United States', 'Honolulu', '57 Carpenter Circle', '96850');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (107, 'United States', 'Chandler', '5 Barby Plaza', '85246');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (108, 'United States', 'Miami', '043 Lakewood Gardens Alley', '33175');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (109, 'United States', 'Saint Paul', '0971 Butternut Pass', '55103');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (110, 'United States', 'Pensacola', '925 Hollow Ridge Alley', '32595');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (111, 'United States', 'Topeka', '03 4th Road', '66611');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (112, 'United States', 'Philadelphia', '2709 Logan Terrace', '19104');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (113, 'United States', 'Colorado Springs', '10 North Drive', '80920');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (114, 'United States', 'Houston', '773 Heffernan Crossing', '77293');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (115, 'United States', 'Detroit', '834 Fulton Circle', '48206');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (116, 'United States', 'Milwaukee', '08 Eagle Crest Circle', '53205');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (117, 'United States', 'Fort Myers', '6800 Lyons Alley', '33994');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (118, 'United States', 'Springfield', '3 Jay Alley', '62756');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (119, 'United States', 'Inglewood', '0 Mccormick Lane', '90305');
insert into ADDRESS (ADDRESS_ID, COUNTRY, CITY, STREET, POSTAL_CODE) values (120, 'United States', 'Reston', '86601 Mesta Parkway', '20195');

select * from address;