DROP DATABASE bazy_danych1;
CREATE DATABASE bazy_danych1;

USE bazy_danych1;

CREATE TABLE `TRANSACTION_TYPE` (
  `TRANSACTION_TYPE_ID` int,
  `TRANSACTION_NAME` varchar(50),
  PRIMARY KEY (`TRANSACTION_TYPE_ID`)
);

CREATE TABLE `ADDRESS` (
  `ADDRESS_ID` int,
  `COUNTRY` varchar(50),
  `CITY` varchar(50),
  `STREET` varchar(50),
  `POSTAL_CODE` varchar(10),
  PRIMARY KEY (`ADDRESS_ID`)
);

CREATE TABLE `EMPLOYEE` (
  `EMPLOYEE_ID` int,
  `FIRST_NAME` varchar(50),
  `LAST_NAME` varchar(50),
  `PHONE_NUMBER` varchar(12),
  `EMAIL` varchar(50),
  `BIRTH_DATE` date,
  `ADDRESS_ID` int,
  PRIMARY KEY (`EMPLOYEE_ID`),
  FOREIGN KEY (`ADDRESS_ID`) REFERENCES `ADDRESS`(`ADDRESS_ID`)
);

CREATE TABLE `ACCOUNT` (
  `ACCOUNT_ID` int,
  `ESTABLISHMENT_DATE` date,
  `IBAN` varchar(50),
  `BIC` varchar(11),
  PRIMARY KEY (`ACCOUNT_ID`)
);

CREATE TABLE `CONTRACT_TYPE` (
  `CONTRACT_TYPE_ID` int,
  `CONTRACT_NAME` varchar(50),
  PRIMARY KEY (`CONTRACT_TYPE_ID`)
);

CREATE TABLE `CONTRACT` (
  `CONTRACT_ID` int,
  `SIGN_DATE` date,
  `EXPIRATION_DATE` date,
  `CONTRACT_TYPE_ID` int,
  `EMPLOYEE_ID` int,
  `ACCOUNT_ID` int,
  PRIMARY KEY (`CONTRACT_ID`),
  FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `EMPLOYEE`(`EMPLOYEE_ID`),
  FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `ACCOUNT`(`ACCOUNT_ID`),
  FOREIGN KEY (`CONTRACT_TYPE_ID`) REFERENCES `CONTRACT_TYPE`(`CONTRACT_TYPE_ID`)
);

CREATE TABLE `CLIENT` (
  `CUSTOMER_ID` int,
  `FIRST_NAME` varchar(50),
  `LAST_NAME` varchar(50),
  `PHONE_NUMBER` varchar(12),
  `EMAIL` varchar(50),
  `BIRTH_DATE` date,
  `CLIENT_TYPE_ID` Enum("Private", "Company"),
  `SIGN_DATE` date,
  `CO-OWNER_ID` int,
  `ADDRESS_ID` int,
  PRIMARY KEY (`CUSTOMER_ID`),
  FOREIGN KEY (`ADDRESS_ID`) REFERENCES `ADDRESS`(`ADDRESS_ID`)
);

CREATE TABLE `COMMON_ACCOUNT` (
  `ACCOUNT_ID` int,
  `CUSTOMER_ID` int,
  PRIMARY KEY (`ACCOUNT_ID`, `CUSTOMER_ID`),
  FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CLIENT`(`CUSTOMER_ID`),
  FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `ACCOUNT`(`ACCOUNT_ID`)
);

CREATE TABLE `TRANSACTION` (
  `TRANSACTION_ID` int,
  `SEND_DATE` date,
  `AMOUNT` decimal(13,4),
  `STATUS` Enum("Complete", "Denied"),
  `TRANSACTION_TYPE_ID` int,
  `SENDER` int,
  `RECEIVER` int,
  PRIMARY KEY (`TRANSACTION_ID`),
  FOREIGN KEY (`RECEIVER`) REFERENCES `ACCOUNT`(`ACCOUNT_ID`),
  FOREIGN KEY (`TRANSACTION_TYPE_ID`) REFERENCES `TRANSACTION_TYPE`(`TRANSACTION_TYPE_ID`),
  FOREIGN KEY (`SENDER`) REFERENCES `ACCOUNT`(`ACCOUNT_ID`)
);

CREATE TABLE `CARD` (
  `NUMBER` varchar(20),
  `EXPIRATION_DATE` date,
  `CVV_NUMBER` char(3),
  `STATUS` Enum("Active", "Inactive"),
  `TRANSACTION_LIMIT` int,
  `ACCOUNT_ID` int,
  `CUSTOMER_ID` int,
  PRIMARY KEY (`NUMBER`),
  FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `ACCOUNT`(`ACCOUNT_ID`),
  FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CLIENT`(`CUSTOMER_ID`)
);

