USE bazy_danych1;

#use case 1
SELECT ADDRESS_ID FROM ADDRESS ORDER BY ADDRESS_ID;
INSERT INTO ADDRESS VALUES (121, 'United States', 'Sacramento', '875 Chive Place', '95818');
SELECT CUSTOMER_ID FROM CLIENT ORDER BY CUSTOMER_ID;
INSERT INTO CLIENT VALUES (61, 'Andrew', 'Soldier', '123456789', 'andsol@gmail.com', '2001-05-13', 'Private', sysdate(), null, 121);

#use case 2
INSERT INTO ACCOUNT VALUES (61, SYSDATE(), 'IS25 4511 6028 4237 0210 7374 00', 'AIBCGG3X');
INSERT INTO COMMON_ACCOUNT VALUES (61, 61);
INSERT INTO CONTRACT VALUES (129, SYSDATE(), '2027-05-30', 1, 15, 61);
INSERT INTO CONTRACT VALUES (130, SYSDATE(), '2027-05-30', 4, 15, 61);
INSERT INTO CARD VALUES ('2545116028423702', '2027-05-30', 257, 'Active', 1000, 61, 61);

#use case 3
INSERT INTO TRANSACTION  VALUES (251, SYSDATE(), 451.00, 'Complete', 3, NULL, (SELECT ACCOUNT_ID FROM ACCOUNT WHERE IBAN LIKE 'LB39 7628 8T19 GAEF SQIJ UG15 ZXUN'));

#use case 4
INSERT INTO TRANSACTION  VALUES (252, SYSDATE(), 451.00, 'Complete', 4, (SELECT ACCOUNT_ID FROM ACCOUNT WHERE IBAN LIKE 'LB39 7628 8T19 GAEF SQIJ UG15 ZXUN'), NULL);

#use case 5
INSERT INTO TRANSACTION  VALUES (253, SYSDATE(), 451.00, 'Complete', 4, (SELECT ACCOUNT_ID FROM ACCOUNT WHERE IBAN LIKE 'LB39 7628 8T19 GAEF SQIJ UG15 ZXUN'), NULL);

#use case 6
SELECT TRANSACTION_ID, SEND_DATE, AMOUNT, STATUS, TRANSACTION_TYPE_ID, SENDER, RECEIVER FROM TRANSACTION
INNER JOIN ACCOUNT ON (TRANSACTION.SENDER = ACCOUNT.ACCOUNT_ID OR TRANSACTION.RECEIVER = ACCOUNT.ACCOUNT_ID)
INNER JOIN COMMON_ACCOUNT ON (ACCOUNT.ACCOUNT_ID = COMMON_ACCOUNT.ACCOUNT_ID)
INNER JOIN CLIENT ON (COMMON_ACCOUNT.CUSTOMER_ID = CLIENT.CUSTOMER_ID)
WHERE CLIENT.FIRST_NAME LIKE 'Aldo' AND  CLIENT.LAST_NAME LIKE 'Ort';

#use case 7
SELECT 
		(SELECT COALESCE(SUM(AMOUNT),0) AS RECEIVER_SUM FROM TRANSACTION
        INNER JOIN ACCOUNT ON (TRANSACTION.SENDER = ACCOUNT.ACCOUNT_ID OR TRANSACTION.RECEIVER = ACCOUNT.ACCOUNT_ID)
		INNER JOIN COMMON_ACCOUNT ON (ACCOUNT.ACCOUNT_ID = COMMON_ACCOUNT.ACCOUNT_ID)
		INNER JOIN CLIENT ON (COMMON_ACCOUNT.CUSTOMER_ID = CLIENT.CUSTOMER_ID)
		WHERE TRANSACTION.RECEIVER = ACCOUNT.ACCOUNT_ID AND CLIENT.FIRST_NAME LIKE 'Andrew' AND  CLIENT.LAST_NAME LIKE 'Soldier'
		AND STATUS LIKE 'Complete')
        -
        (SELECT COALESCE(SUM(AMOUNT),0) AS SENDER_SUM FROM TRANSACTION
        INNER JOIN ACCOUNT ON (TRANSACTION.SENDER = ACCOUNT.ACCOUNT_ID OR TRANSACTION.RECEIVER = ACCOUNT.ACCOUNT_ID)
		INNER JOIN COMMON_ACCOUNT ON (ACCOUNT.ACCOUNT_ID = COMMON_ACCOUNT.ACCOUNT_ID)
		INNER JOIN CLIENT ON (COMMON_ACCOUNT.CUSTOMER_ID = CLIENT.CUSTOMER_ID)
		WHERE TRANSACTION.SENDER = ACCOUNT.ACCOUNT_ID AND CLIENT.FIRST_NAME LIKE 'Andrew' AND  CLIENT.LAST_NAME LIKE 'Soldier' AND
		STATUS LIKE 'Complete') AS ACCOUNT_BALANCE;

#use case 8
INSERT INTO TRANSACTION VALUES (256, SYSDATE(), 451.00, 'Complete', 2, NULL, (SELECT ACCOUNT_ID FROM ACCOUNT WHERE IBAN LIKE 'IS60 8821 2400 3108 6305 9918 78'));

SELECT 	SUM(AMOUNT) AS TOTAL_ACCOUNT_LOAN FROM TRANSACTION 					-- sprawdzamy na ile zapozyczyl sie klient
        INNER JOIN ACCOUNT ON (TRANSACTION.SENDER = ACCOUNT.ACCOUNT_ID OR TRANSACTION.RECEIVER = ACCOUNT.ACCOUNT_ID)
		INNER JOIN COMMON_ACCOUNT ON (ACCOUNT.ACCOUNT_ID = COMMON_ACCOUNT.ACCOUNT_ID)
		INNER JOIN CLIENT ON (COMMON_ACCOUNT.CUSTOMER_ID = CLIENT.CUSTOMER_ID)
		WHERE TRANSACTION.RECEIVER = ACCOUNT.ACCOUNT_ID AND CLIENT.FIRST_NAME LIKE 'Kim' AND  CLIENT.LAST_NAME LIKE 'Addis'
		AND STATUS LIKE 'Complete' AND TRANSACTION.TRANSACTION_TYPE_ID = 2;

#use case 9
UPDATE CLIENT SET EMAIL = 'newemail@gmail.com' WHERE CUSTOMER_ID = 61;

#use case 10
UPDATE CARD SET TRANSACTION_LIMIT = 2000 WHERE ACCOUNT_ID = 61;